version: "3.9"
services:
   nginx:
     image: nginx
     container_name: nginx
     ports:
       - 80:80  
     volumes:
         - ./nginx/conf.d:/etc/nginx/conf.d
         - ./www/:/var/www/html/
   php:
     build: ./php/
     container_name: php
     expose:
       - 9000         
     volumes:
         - ./www/:/var/www/html/
   db:    
      image: mariadb
      restart: unless-stopped  
      container_name: db
      volumes: 
          - ./mysql/data:/var/lib/mysql
          - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:  
       MYSQL_ROOT_PASSWORD: 1234567890
       MYSQL_DATABASE: first_datatbase
   phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
          - 81:80
        depends_on:
          - db
