services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www/:/var/www/html
      - ./certbot/www:/var/www/certbot 
      - ./certbot/conf:/etc/letsencrypt 
    depends_on:
      - php

  php:
    build: ./php/
    container_name: php
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/

  db:
    image: mariadb:latest
    restart: unless-stopped
    container_name: db
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: first_database

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "81:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234567890 
    depends_on:
      - db